project:
  type: website

website:
  title: "IS415 G10 Group Prject: [Project Title]"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

