project:
  type: website

website:
  title: "IS415 G10"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: overview.qmd
        text: Project Overview
      - href: proposal.qmd
        text: Project Proposal
      - href: guide.qmd
        text: User Guide
      - href: poster.qmd
        text: Poster
      - href: "https://haiyangeason.shinyapps.io/is415g10/"
        text: ShinyApp
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual